# Generated by Django 6.0.1 on 2026-01-17 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='token_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
